--- CRIA플O DA TABELA CARDAPIO E PERFIL JURIDICO

-- USANDO O BANCO DE DADOS SABORIA
USE Saboria;


-- FAZ A VERIFICA플O SE EXISTE UMA TABELA COM ESSE NOME E SE EXISTIR ELE APAGA

IF (OBJECT_ID(N'[dbo].[Cardapio]', 'U') IS NOT NULL)
	BEGIN
		DROP TABLE Cardapio
	END
GO

--CRIA플O DA TABELA RESTAURANTE 

CREATE TABLE Cardapio (
    ID_Cardapio INTEGER IDENTITY PRIMARY KEY,
    Nome VARCHAR(120),
    Tipo VARCHAR(80),
    Preco FLOAT,
    StatusVenda VARCHAR(50)
);

--ADD CONSTRAONT DE CHECK STATUS DE VENDA

ALTER TABLE Cardapio ADD CONSTRAINT Cardapio_StatusVenda_Ck 
CHECK (StatusVenda IN('Ativo', 'Pausado'));



-- FAZ A VERIFICA플O SE EXISTE UMA TABELA COM ESSE NOME E SE EXISTIR ELE APAGA


IF (OBJECT_ID(N'[dbo].[PerfilJuridico]', 'U') IS NOT NULL)
	BEGIN
		DROP TABLE PerfilJuridico
	END
GO

--CRIA플O DA TABELA RESTAURANTE 
CREATE TABLE PerfilJuridico (
    ID_PerfilJuridico INTEGER IDENTITY PRIMARY KEY 
);

